### ISSUE TITLE
Initial functionality

### ISSUE THREAD

**Issue by docktermj** [Senzing/ansible-role-stream-producer#3]
**Is your feature request related to a problem? Please describe.**
Create an ansible role that is based on 

```
sudo curl -X GET \
  --output /usr/local/bin/stream-producer.py \
  https://raw.githubusercontent.com/Senzing/stream-producer/master/stream-producer.py

sudo chmod +x /usr/local/bin/stream-producer.py
```

For a pinned version, it would look like this:
```
sudo curl -X GET \
  --output /usr/local/bin/stream-producer.py \
https://raw.githubusercontent.com/Senzing/stream-producer/1.2.2/stream-producer.py

sudo chmod +x /usr/local/bin/stream-producer.py
```

**Comment by docktermj** [comment]
A thought:

A consumer may want to have the `stream-producer.py` file in a different location.  They may also want to rename the python file to avoid a naming conflict.   To work with these situations, we may want to make the ultimate location of the file user definable.   So the representation of the installation may be more like this:

```
export SENZING_LOCATION_STREAM_PRODUCER=/path/to/my/xyz-producer.py

sudo curl -X GET \
  --output ${SENZING_LOCATION_STREAM_PRODUCER:-/usr/local/bin/stream-producer.py} \
https://raw.githubusercontent.com/Senzing/stream-producer/master/stream-producer.py

sudo chmod +x  ${SENZING_LOCATION_STREAM_PRODUCER:-/usr/local/bin/stream-producer.py} 
```

Note the use of `SENZING_LOCATION_` prefix.  It is intentional so that this information would collate in a list.  Example:
```
SENZING_Axxxx=...
SENZING_Bxxxx=...
SENZING_LOCATION_SENZING_UP=/path/to/my/senzing-up.py
SENZING_LOCATION_STREAM_LOADER=/path/to/my/xyz-loader.py
SENZING_LOCATION_STREAM_PRODUCER=/path/to/my/xyz-producer.py
SENZING_Yxxxx=...
SENZING_Zxxxx=...
```
If there's a good argument for a better naming convention, use it.

**Comment by mahchiahui** [comment]
finished updating ansible role

**Comment by mahchiahui** [comment]
working on molecule

**Comment by mahchiahui** [comment]
completed molecule

**Comment by mahchiahui** [comment]
tested git action

**Comment by docktermj** [comment]
Had to get "senzing" namespace on https://galaxy.ansible.com/senzing

We got the namespace by filing an issue: https://github.com/ansible/galaxy/issues/2498
