### ISSUE TITLE
Automate Ansible Galaxy Import

### ISSUE THREAD

**Issue by mahchiahui** [Senzing/ansible-role-stream-producer#5]
**Is your feature request related to a problem? Please describe.**
Currently, an administrator would have to manually import a role on Ansible galaxy every time a new release is made.
Allow ansible galaxy to pass to ansible role variables

**Describe the solution you'd like**
Upon making a new release to Github, Ansible Galaxy would automatically import the latest release.
Pass a variable to ansible galaxy that determines the version of ansible role used

**Comment by docktermj** [comment]
One thought is to use Travis to "catch" a release in GitHub and push to Ansible Galaxy.
